server:
  port: 9000

spring:
  application:
    name: demo

  sql:
    init:
      platform: mysql

  datasource:
    url: jdbc:mysql://muggle.ctizjtx2utrj.ap-northeast-2.rds.amazonaws.com:3306/mydb?autoReconnect=true&setTimezone=Asia/Seoul
    username: muggle # Database ID
    password: UmcMuggleServer^^!!^^ # Database Password
    driver-class-name: com.mysql.cj.jdbc.Driver